#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source custom aliases.
if [[ -s "${ZDOTDIR:-$HOME}/.aliases" ]]; then
  source "${ZDOTDIR:-$HOME}/.aliases"
fi

# Customize to your needs...

# Add command line completion to 'mark' command. 
# see https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org 
compdef _files mark 

# Initialize rbenv - see https://github.com/rbenv/rbenv#homebrew-on-macos
eval "$(rbenv init -)"
